version: '3.8'

services:
  webhook-converter:
    image: nicolasansom/home-assistant-webhook-converter:1.0.0
    container_name: webhook-converter
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/src/app/logs
